const {test,expect,_electron}=require('@playwright/test');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
let electron,page,directory;test.describe.configure({mode:'serial'});
test.beforeAll(async()=>{directory=fs.mkdtempSync(path.join(os.tmpdir(),'qwen-desktop-'));electron=await _electron.launch({args:[path.join(__dirname,'desktop-launch.cjs')],env:{...process.env,QWEN_TEST_DIRECTORY:directory}});page=await electron.firstWindow();await expect(page.getByRole('heading',{name:'创作台',exact:true})).toBeVisible();});
test.afterAll(async()=>{if(electron)await electron.close();if(directory)fs.rmSync(directory,{recursive:true,force:true,maxRetries:5,retryDelay:100});});
test('real Electron sandbox exposes only narrow bridge and DPAPI ciphertext',async()=>{expect(await page.evaluate(()=>({node:typeof require,process:typeof process,keys:Object.keys(window.studio)}))).toMatchObject({node:'undefined',process:'undefined'});const state=await page.evaluate(()=>window.studio.bootstrap());expect(state.credentials).toEqual({hasAPIKey:true,hasChatKey:true,encryptionAvailable:true});expect(JSON.stringify(state)).not.toContain('TEST_ONLY');expect(fs.readFileSync(path.join(directory,'credentials.bin')).includes('TEST_ONLY')).toBe(false);expect(await electron.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration};})).toEqual({sandbox:true,contextIsolation:true,nodeIntegration:false});});
test('actual UI preflight cancel does not call provider and keyboard path stays usable',async()=>{await page.getByRole('button',{name:'生成音频',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('1 次付费调用');await page.getByRole('button',{name:'取消',exact:true}).click();expect(fs.existsSync(path.join(directory,'provider-calls.json'))).toBe(false);await page.getByLabel('音频脚本',{exact:true}).fill('【旁白】一次且仅一次的生成。');await expect(page.getByText('已保存到本地',{exact:true})).toBeVisible();});
test('real bridge deduplicates confirmed calls, validates audio and returns no secrets',async()=>{const state=await page.evaluate(()=>window.studio.bootstrap());const preflight=await page.evaluate(draft=>window.studio.preflight({draft,candidates:1}),state.draft);await page.evaluate(async token=>Promise.all([window.studio.submit(token),window.studio.submit(token)]),preflight.token);expect(JSON.parse(fs.readFileSync(path.join(directory,'provider-calls.json'))).calls).toBe(1);const result=await page.evaluate(()=>window.studio.bootstrap());expect(result.tasks[0].status).toBe('success');expect(result.tasks[0].duration).toBe(1);expect(JSON.stringify(result)).not.toContain('fake.invalid');expect(JSON.stringify(result)).not.toContain('TEST_ONLY');const audio=await page.evaluate(id=>window.studio.readAudio({kind:'task',id}).then(value=>({size:value.data.length,mime:value.mimeType})),result.tasks[0].id);expect(audio.size).toBe(192044);expect(audio.mime).toBe('audio/wav');await expect(page.locator('audio')).toHaveCount(1);});
test('main refuses arbitrary file IDs and canceled consent, trash restoration preserves actual file',async()=>{expect(await page.evaluate(()=>window.studio.readAudio({kind:'task',id:'../../credentials.bin'}).then(()=>false,()=>true))).toBe(true);const state=await page.evaluate(()=>window.studio.bootstrap());const preflight=await page.evaluate(draft=>window.studio.preflight({draft,candidates:1}),state.draft);await page.evaluate(token=>window.studio.cancelPreflight(token),preflight.token);expect(await page.evaluate(token=>window.studio.submit(token).then(()=>false,()=>true),preflight.token)).toBe(true);await page.evaluate(id=>window.studio.updateTask({id,trashed:true}),state.tasks[0].id);await page.evaluate(id=>window.studio.updateTask({id,trashed:false}),state.tasks[0].id);const paths=JSON.parse(fs.readFileSync(path.join(directory,'studio.json'))).tasks[0];expect(fs.existsSync(paths.outputPath)).toBe(true);});
test('chat through real bridge imports safe plain-text script and no renderer networking',async()=>{await page.getByRole('navigation').getByRole('button',{name:'AI 编剧',exact:true}).click();await page.getByLabel('创作需求').fill('一段旁白');await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.getByRole('button',{name:'导入创作台',exact:true})).toBeVisible();expect(await page.evaluate(()=>fetch('https://example.com').then(()=>false,()=>true))).toBe(true);await page.screenshot({path:'test-results/windows-desktop-scriptwriter.png'});});
test('bundled Chromium decodes valid MP3 and rejects corrupt MPEG frames',async()=>{const valid=[...fs.readFileSync(path.join(__dirname,'fixtures/synthetic-tone.mp3'))];const result=await electron.evaluate(async(_electron,bytes)=>globalThis.qaDecode({data:Buffer.from(bytes),params:{sampleRate:48000,channels:2}}),valid);expect(result.duration).toBeGreaterThan(.9);expect(result.duration).toBeLessThan(1.2);const rejected=await electron.evaluate(async()=>{const corrupt=Buffer.alloc(417*4,255);for(let offset=0;offset<corrupt.length;offset+=417)Buffer.from([255,251,144,0]).copy(corrupt,offset);try{await globalThis.qaDecode({data:corrupt,params:{sampleRate:44100,channels:2}});return false;}catch{return true;}});expect(rejected).toBe(true);});
test('native encrypted credentials and persisted draft survive process restart',async()=>{await electron.close();electron=await _electron.launch({args:[path.join(__dirname,'desktop-launch.cjs')],env:{...process.env,QWEN_TEST_DIRECTORY:directory}});page=await electron.firstWindow();await expect(page.getByRole('heading',{name:'创作台',exact:true})).toBeVisible();const state=await page.evaluate(()=>window.studio.bootstrap());expect(state.tasks[0].status).toBe('success');expect(state.credentials.hasAPIKey).toBe(true);expect(JSON.parse(fs.readFileSync(path.join(directory,'provider-calls.json'))).calls).toBe(1);});

test('closing immediately after typing flushes debounced draft to disk',async()=>{await page.getByRole('navigation').getByRole('button',{name:'创作台',exact:true}).click();await page.getByLabel('音频脚本',{exact:true}).fill('关闭时也不能丢失的新草稿。');const closing=page.waitForEvent('close');await electron.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await closing;expect(JSON.parse(fs.readFileSync(path.join(directory,'studio.json'))).draft.prompt).toBe('关闭时也不能丢失的新草稿。');electron=null;});
